# Generated by Django 4.1.2 on 2022-11-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(max_length=64, unique=True, verbose_name="نام"),
                ),
            ],
            options={
                "verbose_name": "نام",
                "verbose_name_plural": "نام ها",
            },
        ),
        migrations.CreateModel(
            name="ModelName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=64, unique=True, verbose_name="مدل"),
                ),
            ],
            options={
                "verbose_name": "مدل",
                "verbose_name_plural": "مدل ها",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=32, verbose_name="برند")),
                (
                    "status",
                    models.CharField(
                        choices=[("خ", "خراب"), ("س", "سالم")],
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                ("data_created", models.DateTimeField(auto_now_add=True)),
                ("regular_checks", models.PositiveIntegerField()),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Mname",
                        to="devices.modelname",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Dname",
                        to="devices.devicename",
                    ),
                ),
            ],
            options={
                "verbose_name": "دستگاه",
                "verbose_name_plural": "دستگاه ها",
            },
        ),
    ]
