# Generated by Django 4.1.2 on 2022-11-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=64)),
                ("brand", models.CharField(max_length=32)),
                ("status", models.BooleanField(default=True)),
                ("data_created", models.DateTimeField(auto_now_add=True)),
                ("regular_checks", models.SmallIntegerField()),
            ],
            options={
                "ordering": ["status"],
            },
        ),
    ]
