# Generated by Django 4.1.2 on 2022-11-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={"ordering": ["regular_checks", "-status"]},
        ),
        migrations.AlterField(
            model_name="device",
            name="regular_checks",
            field=models.PositiveIntegerField(),
        ),
    ]
