# Generated by Django 4.1.2 on 2022-11-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_alter_device_options_alter_device_regular_checks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={
                "ordering": ["regular_checks", "-status"],
                "verbose_name": "دستگاه",
                "verbose_name_plural": "دستگاه ها",
            },
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[("س", "سالم"), ("خ", "خراب")], max_length=1
            ),
        ),
    ]
