# Generated by Django 4.1.3 on 2022-11-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_options_alter_device_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'دستگاه', 'verbose_name_plural': 'دستگاه ها'},
        ),
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.CharField(max_length=32, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(max_length=64, verbose_name='مدل'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=64, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('س', 'سالم'), ('خ', 'خراب')], max_length=10, verbose_name='وضعیت'),
        ),
    ]
