# Generated by Django 4.1.3 on 2022-11-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_options_alter_device_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('خ', 'خراب'), ('س', 'سالم')], max_length=10, verbose_name='وضعیت'),
        ),
    ]
