# Generated by Django 4.1.2 on 2022-11-28 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_alter_device_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Sname",
                to="devices.statusname",
            ),
        ),
    ]
